import Head from "next/head";
import Image from "next/image";
import { Sora } from "next/font/google";
import { Box } from "@chakra-ui/react";
import ClubLookUp from "@/components/club-lookup";

const sora = Sora({ subsets: ["latin"], weight: ["500", "700"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Footium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${sora.className}`}>
        <Box
          display="flex"
          flexDirection="column"
          alignItems="center"
          justifyContent="center"
          color="gray.300"
          padding="5vw"
        >
          <Box
            display="flex"
            flexDirection="column"
            alignItems="center"
            justifyContent="center"
            bg="black"
            gap="40px"
          >
            <Image
              src="/assets/footium.png"
              width={400}
              height={400}
              alt="logo"
            />
            <ClubLookUp />
          </Box>
        </Box>
      </main>
    </>
  );
}
